---
- hosts: devops
  sudo: yes

  vars:
    - repo: https://github.com/Aetrix27/Chat-App-using-Socket.io
    - homeDir : /home/ubuntu
    - appDir: app
    - private_key : /Users/David/.ssh/id_rsa
    - github_name : aetrix27

  tasks:
    -name: Install Packages
      apt: name = {{item }} update_cache=yes state=latest 
      with_items:
        - build-essential
        - npm
        - mcrypt
        - nginx
        - curl
        - nodejs-legacy
        - git
    -name: Install pm2
      npm: name=pm2 global=yes production=yes

    -name: Create APP Directory
     file = path={{homeDir}}/{{appDir}} state=directory
    
    -name: Copy PK
    copy: src = {{private_key}} dest = {{homeDir}} mode=0600

    -name: Clone Git Repo
    git: repo=git@github.com:{{github_name}}/{{repo}}.git dest = {{homeDir}}/{{appDir}} update=yes force=yes accept_hostkeys  key_file={{homeDir}}/id_rsa
    register: git_finished

    - name: Running NPM install
      npm: path={{homeDir}}/{{appDir}}/backend
      register: npm_finished
      when: git_finished.changed
    
    -name: Stop APP 
      sudo_user: ubuntu
      command: pm2 stop app chdir={{homeDir}}
      ignore_errors: yes
    
    -name: Start APP
        sudo_user: ubuntu
        command: pm2 start index.js --name app chdir={{homeDir}}/{{appDir}}/backend
        ignore_errors: yes
        when: npm_finished.changed

    
