---
- hosts: localhost
  gather_facts: no
  become: yes

  vars:
      git_repo: https://github.com/Aetrix27/Chat-App-using-Socket.io
      local_repo_path: /home/ubuntu
      repo_branch: master

  tasks: 
  - name: Run apt-get update
    apt:
     update_cache: yes
  - name: Ansible shell commands
    shell: 'curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -'
  - name: Install packages
    apt: name={{ item }} state=present
    with_items:
      - nodejs
      - nginx
      - git
      - wget
      - curl

  - name: Clone a private repository
    git:
      repo: "{{ git_repo }}"
      version: "{{ repo_branch }}"
      dest: "{{ local_repo_path }}"
      accept_hostkey: yes
  - name: npm install package.json
    npm:
      path: "{{ local_repo_path }}"
      state: present
  - name: Build app
    command: npm run build
    args:
      chdir: "{{ local_repo_path }}"
  - name: Copy folder to /var/www
    copy:
     src: "{{ local_repo_path }}/build"
     dest: /var/www
     remote_src: no
  
- name: Recursively change ownership of a directory
    file:
        path: /etc/nginx/SSL
        state: directory
        recurse: yes
  - name: Retrieve OpenSSH key pair
    copy:
        owner: root
        group: root
        src: "{{ item.0 }}"
        dest: "{{ item.1 }}"
        mode: "0400"
      with_together:
        - ['local_path/example.crt', 'local_path/example.key', 'example.conf']
        - ['/etc/nginx/SSL/example.crt', '/etc/nginx/SSL/example.key', '/etc/nginx/sites-available/example.conf']

  - name: Makes a link
    file:
      src: /etc/ngnix/sites-available/example.conf
      dest: /etc/nginx/sites-enabled/example.conf
      state: link
  - name: Remove files
    file:
     path: "{{ item }}"
     state: absent
    with_items:
      - /etc/nginx/sites-enabled/default
      - /etc/nginx/sites-available/default

  - name: Restart nginx 
    service:
      name: nginx
      state: restarted